In [2]:
import numpy as np

### A

In [3]:
##### np.array.tolist()
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [3, 3, 3, 3]])
print(arr)
# Convert 2D Numpy Array to list of lists
list_of_lists = arr.tolist()
print(list_of_lists)  

[[1 2 3 4]
 [5 6 7 8]
 [3 3 3 3]]
[[1, 2, 3, 4], [5, 6, 7, 8], [3, 3, 3, 3]]


### N
##### None vs np.nan

In [9]:
# None
a = [0, 1, None, 0]
a_array = np.array(a)
print(a)
print(a_array)
print(a_array.dtype)

# np.nan
b = [0, 1, np.nan, 0]
b_array = np.array(b)
print(b)
print(b_array)
print(b_array.dtype)

[0, 1, None, 0]
[0 1 None 0]
object
[0, 1, nan, 0]
[ 0.  1. nan  0.]
float64


### R
##### Difference between np.random.random and numpy.random.uniform
See https://stackoverflow.com/questions/13213496/what-does-depending-on-rounding-exactly-mean/13213524#13213524


In [2]:
np.random.random()          # has no arguments, returns a float in [0, 1)
np.random.uniform(5, 10)    # can have arguments, can return float in [5, 10) or in [5, 10] depending on rounding

6.163090954304306

### W

In [5]:
a = [0, 1, None, 0]
print(np.where(a)[0]) # returns the indices of the non-zero and not None elements
print(np.where(np.array(a) is not None)[0]) # returns the indices of the non-zero and not None elements

[1]
[0]
